name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864ff69b85d7a09b90ae7106e95ee2607e485e4f791f85fbea4c29c0d8978154"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
