name = "Wold's Vaults"
author = "iwolfking"
version = "0.22.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b5f3b691dedcedd539f3ca2524763fb63fedb359f32351cb0c58c15611b4e96"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
